# Site settings
title: "The homepage  of CoRR-VIEW on freenode"
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Homepage & rules of ##CoRR on freenode IRC network.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://faical-yannick-congo.github.io" # the base hostname & protocol for your site
#twitter_username: abgilpqt
github_username:  faical-yannick-congo

# Build settings
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Etc/UTC
encoding: utf-8
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"